# Generated by Django 2.2.3 on 2019-10-01 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='_locked_by',
            field=models.ForeignKey(db_column='blocked_by', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_on_locking_lock', to=settings.AUTH_USER_MODEL),
        ),
    ]
